config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/terms_of_service', to: 'pages#terms_of_service'
  get '/contact', to: 'pages#contact'
  get '/comment_form', to: 'pages#comment_form'
  get '/steps', to: 'pages#steps'
  get '/checkup', to: 'pages#checkup'

  get '/hello', to: 'hello#index'

  devise_for :admin_users, only: [:sessions], controllers: {
    sessions: 'admin_users/sessions',
  }
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions',
  }
  devise_for :employees, controllers: {
    registrations: 'employees/registrations',
    sessions: 'employees/sessions',
  }

  resources :admin_users, only: [:show]
  resources :students, only: [:show] do
    resources :course_orders, controller: 'students/course_orders', only: [:index, :create, :destroy]
    resources :internships, controller: 'students/internships', only: [:index]
    resources :internship_carts, controller: 'students/internship_carts', only: [:create, :destroy]
    resources :internship_orders, controller: 'students/internship_orders', only: [:create] do
      post '/contact', to: 'students/internship_orders#contact'
    end
  end
  resources :employees, only: [:show] do
    resources :course_orders, controller: 'employees/course_orders', only: [:index, :create, :destroy]
  end
  resources :internships, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :announcements, only: [:index, :show]

  resources :companies, only: [:index, :show, :edit, :update] do
    resources :internships, controller: 'companies/internships'
  end

  namespace :admin do
    resources :admin_users
    resources :students
    resources :student_details
    resources :business_categories
    resources :companies
    resources :employees
    resources :employee_details
    resources :internship_categories
    resources :internship_attendance_types
    resources :internships
    resources :internship_carts
    resources :internship_orders
    resources :course_categories
    resources :course_attendance_types
    resources :courses
    resources :student_course_orders
    resources :employee_course_orders
    resources :announcement_categories
    resources :announcements
    resources :nagaoka_companies

    root to: "companies#index"
  end

  get '/admin/mailers/form', to: 'admin_mailers#form'
  post '/admin/mailers/post', to: 'admin_mailers#post'
end

app/models/company.rb
class Company < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }
  validates :business_category_id, presence: true
  validates :address, presence: false, length: { maximum: 100 }
  validates :contact_phone_number, presence: true
  validates :contact_name, presence: true, length: { maximum: 100 }
  validates :contact_email, presence: true
  validates :number_of_employee, numericality: { only_integer: true, greater_than_or_equal_to: 0 }, allow_blank: true

  belongs_to :business_category
  has_many :employees, dependent: :destroy
  has_many :internships, dependent: :destroy
  has_one_attached :thumbnail

  def image_urls
    array = [thumbnail.representation(resize_to_limit: [800, 800])] if thumbnail.representable?
    array = ['no_image.png'] if array.empty?
    array
  end
end

app/controllers/admin/companies_controller.rb
module Admin
  class CompaniesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/companies/internships_controller.rb
class Companies::InternshipsController < ApplicationController
  before_action :authenticate_employee!
  before_action :validate_company!

  def index
    @internships = Internship.where(company_id: params[:company_id])
    @company = Company.find(params[:company_id])
  end

  def show
    @internship = Internship.find(params[:id])
    @company = @internship.company
  end

  def new
    @internship = Internship.new
    @company = Company.find(params[:company_id])
  end

  def edit
    @internship = Internship.find(params[:id])
    @company = @internship.company
  end

  def create
    a = internship_params
    a[:company_id] = params[:company_id].to_i
    @internship = Internship.new(a)
    @company = Company.find(params[:company_id])

    if @internship.save
      redirect_to company_internships_path, notice: "Internship was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @internship = Internship.find(params[:id])
    @company = @internship.company

    if @internship.update(internship_params)
      redirect_to company_internship_path(id: @internship.id), notice: "Internship was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @internship = Internship.find(params[:id])
    @internship.destroy
    redirect_to company_internships_url(@internship.company), notice: "Internship was successfully destroyed."
  end

  private

  def validate_company!
    redirect_to root_path, alert: "権限がありません" if params[:company_id].to_i != current_employee.company.id
  end

  def internship_params
    params.require(:internship).permit(
      :title, :description, :start_date, :end_date, :deadline,
      :location, :target, :thumbnail, :acceptable_number, :others, :company_id,
      :internship_attendance_type_id, :internship_category_id
    )
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_employee!, only: [:edit, :update]
  before_action :set_company, only: [:edit, :update]

  def index
    @companies = Company.where(is_public: true)
  end

  def show
    @company = Company.find(params[:id])
  end

  def edit
  end

  def update
    if @company.update(company_params)
      redirect_to employee_path(current_employee), notice: "Company was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_company
    redirect_to root_path, alert: "権限がありません" if params[:id].to_i != current_employee.company.id
    @company = Company.find(current_employee.company.id)
  end

  def company_params
    params.require(:company).permit(
      :name, :company_url, :contact_phone_number, :business_category_id, :address,
      :business_description, :number_of_employee, :contact_name, :contact_email
    )
  end
end

app/views/companies/edit.html.erb
<%= render 'partial/employee_mypage_layout' do %>
<h2 class="mb-4">企業情報編集</h2>

<%= bootstrap_form_with(model: @company, url: company_path, method: :put, local: true) do |f| %>
<%= f.text_field :name %>
<%= f.text_field :company_url %>
<%= f.collection_select :business_category_id, BusinessCategory.all, :id, :name, { include_blank: "選択してください" } %>
<%= f.text_field :address %>
<%= f.text_area :business_description %>
<%= f.number_field :number_of_employee %>
<%= f.text_field :contact_name %>
<%= f.telephone_field :contact_phone_number %>
<%= f.email_field :contact_email %>
<%= f.file_field :thumbnail %>

<%= f.submit "更新する", class: "btn btn-primary mt-3 text-white w-100" %>
<% end %>

<% end %>

app/views/companies/index.html.erb
<div class="my-container">
  <div class="my-5 d-flex gap-4 align-items-center">
    <h2>参加企業一覧</h2>
    <span><%= @companies.size %>件</span>
  </div>

  <div class="row row-cols-md-3 row-cols-2 g-2">
    <% @companies.each do |company| %>
    <div class="col card p-3 border-0">
      <% if company.thumbnail.representable? %>
      <%= link_to image_tag(company.thumbnail.representation(resize_to_limit: [800, 800]), class: 'object-contain w-100'), company, class: "ratio ratio-16x9" %>
      <% else %>
      <%= link_to image_tag("no_image.png", class: "object-fit-cover w-100"), company, class: "ratio ratio-16x9" %>
      <% end %>

      <div class="my-2 flex justify-center">
        <%= link_to company.name, company, class: "no-underline text-slate-800 hover:underline" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="my-container">
  <h2 class="my-5"><%= @company.name %></h2>

  <div class="my-5 md:mx-12">
    <% if @company.thumbnail.representable? %>
    <%= image_tag @company.thumbnail.representation(resize_to_limit: [800, 800]), class: 'w-100' %>
    <% end %>
  </div>

  <table class="table-fixed mt-5 w-100">
    <tbody>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.company_url' %></th>
        <td class="table-td"><%= link_to @company.company_url %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.business_category.name' %></th>
        <td class="table-td"><%= @company.business_category.name %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.address' %></th>
        <td class="table-td"><%= @company.address %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.business_description' %></th>
        <td class="table-td"><%= simple_format(@company.business_description) %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.number_of_employee' %></th>
        <td class="table-td"><%= @company.number_of_employee %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.contact_name' %></th>
        <td class="table-td"><%= @company.contact_name %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.contact_phone_number' %></th>
        <td class="table-td"><%= @company.contact_phone_number %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.company.contact_email' %></th>
        <td class="table-td"><%= @company.contact_email %></td>
      </tr>
    </tbody>
  </table>

  <div class="my-3 text-right">
    <%= link_to "https://nagaoka-shukatsuondemand.jp/all-movie/", :target=>["_blank"], class: "btn btn-primary text-white" do %>
    <i class="bi bi-play-circle-fill"></i> 紹介動画を見る
    <% end %>
  </div>

  <h4 class="my-3">募集中のインターンシップ情報</h4>
  
  <%= render 'partial/internships', internships: @company.internships %>

  <div class="mt-5">
    <i class="bi bi-chevron-left"></i><%= link_to "戻る", companies_path, class: 'link-primary-with-underline' %>
  </div>
</div>