config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/terms_of_service', to: 'pages#terms_of_service'
  get '/contact', to: 'pages#contact'
  get '/comment_form', to: 'pages#comment_form'
  get '/steps', to: 'pages#steps'
  get '/checkup', to: 'pages#checkup'

  get '/hello', to: 'hello#index'

  devise_for :admin_users, only: [:sessions], controllers: {
    sessions: 'admin_users/sessions',
  }
  devise_for :students, controllers: {
    registrations: 'students/registrations',
    sessions: 'students/sessions',
  }
  devise_for :employees, controllers: {
    registrations: 'employees/registrations',
    sessions: 'employees/sessions',
  }

  resources :admin_users, only: [:show]
  resources :students, only: [:show] do
    resources :course_orders, controller: 'students/course_orders', only: [:index, :create, :destroy]
    resources :internships, controller: 'students/internships', only: [:index]
    resources :internship_carts, controller: 'students/internship_carts', only: [:create, :destroy]
    resources :internship_orders, controller: 'students/internship_orders', only: [:create] do
      post '/contact', to: 'students/internship_orders#contact'
    end
  end
  resources :employees, only: [:show] do
    resources :course_orders, controller: 'employees/course_orders', only: [:index, :create, :destroy]
  end
  resources :internships, only: [:index, :show]
  resources :courses, only: [:index, :show]
  resources :announcements, only: [:index, :show]

  resources :companies, only: [:index, :show, :edit, :update] do
    resources :internships, controller: 'companies/internships'
  end

  namespace :admin do
    resources :admin_users
    resources :students
    resources :student_details
    resources :business_categories
    resources :companies
    resources :employees
    resources :employee_details
    resources :internship_categories
    resources :internship_attendance_types
    resources :internships
    resources :internship_carts
    resources :internship_orders
    resources :course_categories
    resources :course_attendance_types
    resources :courses
    resources :student_course_orders
    resources :employee_course_orders
    resources :announcement_categories
    resources :announcements
    resources :nagaoka_companies

    root to: "companies#index"
  end

  get '/admin/mailers/form', to: 'admin_mailers#form'
  post '/admin/mailers/post', to: 'admin_mailers#post'
end

app/controllers/admin/courses_controller.rb
module Admin
  class CoursesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @employee_order = EmployeeCourseOrder.find_by(employee: current_employee, course: @course)
    @student_order = StudentCourseOrder.find_by(student: current_student, course: @course)
  end
end

app/views/courses/index.html.erb
<div class="my-container">
  <div class="my-5 d-flex gap-4 align-items-center">
    <h2>講座一覧</h2>
    <span><%= @courses.size %>件</span>
  </div>
  <%= render 'partial/courses', courses: @courses %>
</div>

app/views/courses/show.html.erb
<div class="my-container">
  <div class="mt-5">
    <span class="badge mb-3"
      style="background-color: <%= @course.course_category.bg_color %>;"><%= @course.course_category.name %></span>
    <h3 class="mb-3"><%= @course.title %></h3>
    <div class="text-slate-600"><%= simple_format(@course.description) %></div>
  </div>

  <div class="my-5 md:mx-12">
    <% if @course.thumbnail.representable? %>
    <%= image_tag @course.thumbnail.representation(resize_to_limit: [800, 800]), class: 'w-100' %>
    <% end %>
  </div>

  <table class="table-fixed my-5 w-100">
    <tbody>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course_attendance_type.name' %></th>
        <td class="table-td"><%= @course.course_attendance_type.name %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.event_date' %></th>
        <td class="table-td"><%= l @course.event_date, format: :ymd %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.deadline' %></th>
        <% if @course.deadline.present? %>
        <td class="table-td"><%= l @course.deadline, format: :ymd %></td>
        <% else %>
        <td class="table-td"></td>
        <% end %>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.place' %></th>
        <td class="table-td"><%= @course.place %></td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.target' %></th>
        <td class="table-td"><%= @course.target %></td>
      </tr>
      <tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.acceptable_number' %></th>
        <td class="table-td"><%= @course.acceptable_number %>名</td>
      </tr>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.others' %></th>
        <td class="table-td"><%= Rinku.auto_link(simple_format(@course.others), :urls, 'target="_blank"').html_safe %></td>
      </tr>
      <% if current_student || current_employee || current_admin_user %>
      <tr>
        <th class="table-th"><%= t 'activerecord.attributes.course.announcement' %></th>
        <td class="table-td"><%= Rinku.auto_link(simple_format(@course.announcement), :urls, 'target="_blank"').html_safe %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="my-5 text-center">
    <% if current_employee && !@employee_order.present? %>
    <%= button_to "申し込む", employee_course_orders_path(current_employee),
      form: { data: { turbo_confirm: "申し込みますか？" } },
      params: { course_id: @course.id },
      class: "btn btn-primary text-white px-5 shadow"
    %>
    <% elsif current_student && !@student_order.present? %>
    <%= button_to "申し込む", student_course_orders_path(current_student),
      form: { data: { turbo_confirm: "申し込みますか？" } },
      params: { course_id: @course.id },
      class: "btn btn-primary text-white px-5 shadow"
    %>
    <% elsif @employee_order.present? || @student_order.present? %>
    <button class="btn disabled">申し込み済み</button>
    <% end %>
  </div>

  <i class="bi bi-chevron-left"></i><%= link_to "戻る", :back, class: 'link-primary-with-underline' %>
</div>